### ISSUE TITLE
No connection from Ingress Pods to Redis Service and persistence problems

### ISSUE THREAD

**Issue by OLED1** [bunkerity/bunkerweb-helm#28]
I am currently having the problem that the ingress pods (managed by the scheduler) can't access the redis service.
Reason for that is, that they want to access the service directly with it's service name instead of the full name: `<svc>`.`<ns>`.cluster.local or something compareable.

```
kubectl -n bunker-ingress-staging logs pods/bunker-ingress-staging-bunkerweb-bsldj
...
2025/05/22 15:59:26 [error] 4685#4685: *5834 [METRICS] Can't connect to Redis server: error while getting redis client : redis-bunker-ingress-staging-bunkerweb could not be resolved (3: Host not found) - requests will be stored in datastore, context: ngx.timer
...
```

I overrided the the ENV "REDIS_HOST" directly in the deployment to the full name and it worked, the connection was able to be established.

I tried to make it persistent the following way:
```
# Scheduler variables
scheduler:
  repository: bunkerity/bunkerweb-scheduler
  pullPolicy: Always
  tag: 1.6.1
  podAnnotations: {}
  podLabels: {}
  securityContext:
    runAsUser: 101
    runAsGroup: 101
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  extraEnvs:
 ...
  - name: REDIS_HOST
    value: "redis-bunker-ingress-staging-bunkerweb.bunker-ingress-staging.svc.cluster.local"
```

But that leads to an duplication error from Bunker, because the `_helpers.tpl` already sets this variable. Overriding by just setting `fullnameOverride' in the `values.yaml' would lead to overriding the naming of other services like the database. So this not the way to go.

I ask you to always use the full name for accessing the Services used and needed by bunker instead of only using the service name or to allow to override every variable previously set by the  `_helpers.tpl`.

Furthermore, I am experiencing persistence errors when restart all pods from the ingress daemonsets: All statistics are disdappearing. I don't know why. The database has a PVC. Redis does not have a persistence either.
Maybe you guys have an idea what's happening.

Thanks you so much for your help.
I hope my requests belongs here because I am sure it's not bunker web itself which causes this issues.
Let me know if you need more information.
